# Generated by Django 3.2 on 2024-01-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
    ]
